name: CI-CD Pipeline
run-name: CI-CD
env: 
    DEPLOY_PACKAGE_NAME : "acebook-node-red_${{ github.sha }}.zip"
    AWS_REGION_NAME : "eu-west-2"
on: [push]

jobs:
    my_ci_part:
        runs-on: ubuntu-latest

        steps:
        - name: Git clone our repo
          uses: actions/checkout@v1

        - name: Create ZIP Deployment Package
          run: zip -r "${{env.DEPLOY_PACKAGE_NAME}}" . -x \*.git\*

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.acebook_access_key }}
            aws-secret-access-key: ${{ secrets.acebook_secret_key }}
            aws-region: ${{ env.AWS_REGION_NAME }}

        - name: Copy Deployment package to S3 bucket
          run: aws s3 sync "${{ env.DEPLOY_PACKAGE_NAME }}" "s3://acebook-red-bucket/"
          

        
    my_cd_part: 
        runs-on: ubuntu-latest
        needs: [my_ci_part]

        steps: 
        - name: Configure my AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with: 
            aws-access-key-id: ${{ secrets.acebook_access_key }}
            aws-secret-access-key: ${{ secrets.acebook_secret_key }}
            aws-region: ${{ env.AWS_REGION_NAME }}

        - name: Deploy to EC2 using CodeDeploy
          run: |
              aws deploy create-deployment \
              --application-name acebook-red \
              --deployment-group-name production-red \
              --s3-location bucket="acebook-red-bucket" \
              --s3-location key="${{ env.DEPLOY_PACKAGE_NAME }}" \
              --s3-location bundleType=zip