name: End-to-end tests
run-name: YAML Deploment
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['5.0']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or the version you require

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          start: npm run start:test
          wait-on: http://localhost:3030
    
      - name: Install dependencies
        run: npm install
      - run: npm test

        env:
          CI: true

      - name: Run Lint
        run: npm run lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZVHCKJRW2XEF7GMC
          aws-secret-access-key: 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
          aws-region: eu-west-2

      - name: Deploy to EC2 using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name acebook-red \
            --deployment-group-name production-red \
            --s3-location bucket=arn:aws:s3:::acebook-red-bucket