name: End-to-end tests
run-name: Setting up node
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or the version you require

      - name: Install dependencies
        run: npm install