name: End-to-end tests
run-name: Setting up node
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or the version you require

      - name: Install dependencies
        run: npm install

      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          start: npm run start:test
          wait-on: http://localhost:3030

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
    
      - run: npm install
    
      - run: npm test
        env:
          CI: true