name: End-to-end tests
run-name: Setting up node
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # or the version you require

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '5.0'

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          start: npm run start:test
          wait-on: http://localhost:3030
    
      - name: Install dependencies
        run: npm install

      - run: npm test
        env:
          CI: true