name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or the version you require

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2 # Make sure to use the correct version
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3030
